services:
  web:
    # Path to the directory containing the Dockerfile (same directory)
    build: .
    # Map the container's internal port to the local machine
    ports:
      - "127.0.0.1:5000:5000"
    # Environment variables
    env_file:
      - EsportsManagementTool/.env
    # Sync local files to the container for live-reloading
    volumes:
      - .:/EsportsManagementTool
