[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EsportsManagementTool"
version = "0.1.0"
description = "Stockton Esports Management Tool"
requires-python = ">=3.9"
dependencies = [
    "flask"
]
